[package]
name = "simple-src-docs"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive", "wrap_help"] }
either = "1.14.0"
regex = "1.11.1"
walkdir = "2.5.0"
